### ISSUE TITLE
jwt认证

### ISSUE THREAD

**Issue by alasai** [AntonyCheng/spring-boot-init-template#2]
1.刚在配置里启用了jwt认证，修改了登录接口返回了jwt字符串，没看到jwt拦截器
2.http://localhost:38080/api/doc.html 这个怎么添加授权按钮 ，之前都是在swagger里面添加的

**Comment by AntonyCheng** [comment]
> 1.刚在配置里启用了jwt认证，修改了登录接口返回了jwt字符串，没看到jwt拦截器
> 
> 2.http://localhost:38080/api/doc.html 这个怎么添加授权按钮 ，之前都是在swagger里面添加的

1、JWT引用的是SaToken鉴权认证框架自带的JWT拦截类，相关代码在src/main/java/top/sharehome/springbootinittemplate/config/security/TokenWithJwtConfiguration.java文件中，我没记错的话SaToken官方文档中有其他整合JWT的方式。
2、模版在老版本整合的是Knife4j+Swagger，为了后续升级成为SpringBoot3，适配Knife4j版本，把Swagger替换成了SpringDoc，你可以在application配置文件中找到knife4j和springdoc的相关配置。
