### ISSUE TITLE
SaToken配置依赖无法注入问题

### ISSUE THREAD

**Issue by Yaeovoi** [AntonyCheng/spring-boot-init-template#3]
AuthorizationConfiguration和TokenWithJwtConfiguration都无法注入依赖配置, 在启动之后并没有看到注入成功的日志输出, 之前配置的OSS的Minio有日志输出, 跟上次一样的配方CV大法过来, 但这次却没成功....排查了好一会, 刚开始以为是没法读取配置文件的信息, 后面才发现是依赖并为注入

**Comment by Yaeovoi** [comment]
![1](https://github.com/AntonyCheng/spring-boot-init-template/assets/140489728/b7556799-79f3-4228-b72b-40c1daa20642)
![2](https://github.com/AntonyCheng/spring-boot-init-template/assets/140489728/a9ee4c56-a9a6-4385-a4a3-956f0835a982)

**Comment by AntonyCheng** [comment]
很抱歉没有能够及时回复你，这两个Bean是注入了的，但是要注入JWT的前提是要在配置文件相关的地方开启它才行，如下图：

![image](https://github.com/AntonyCheng/spring-boot-init-template/assets/88792183/afeb2769-c00e-4d20-8d66-d6988bfd4194)

如果要验证，如下图：

![image](https://github.com/AntonyCheng/spring-boot-init-template/assets/88792183/bb912de9-73ff-44a2-b9e3-d9f02943a11b)

**Comment by AntonyCheng** [comment]
如果有任何问题，尽管提出来一起探讨

**Comment by Yaeovoi** [comment]
![3](https://github.com/AntonyCheng/spring-boot-init-template/assets/140489728/030c69f8-e730-401d-bc9d-256999557e37)
并没有打印出你上图所示的配置 呜呜呜

**Comment by AntonyCheng** [comment]
我从你给出的截图中初步判断，有没有可能是因为你修改了包名，导致没能扫描到你自己的Bean：

![image](https://github.com/AntonyCheng/spring-boot-init-template/assets/88792183/74a04ef3-f5ff-4e90-b650-ee94bef1ab6c)

**Comment by Yaeovoi** [comment]
1. 我把satoken的相关配置都放在common公共模块里了, 我在user模块来使用satoken的jwt+redis的功能
2. 你封装的LoginUtils我在登录方法里用, 是可以使用的, 但我开启了jwt配置发现并不生效 
3. 之前我以为是你忘记注入jwt的配置, 后面发现你里面已经加有了
4. 我根据你前面说的加上扫包, 我也加上了, 但是还是打印不出之前所预想的结果
5. 谢谢你百忙之中抽空来回答我的问题, 不想耽搁你太多时间
6. 可以考虑使用远程工具todesk来进行调试, 如果可以的话加我vx吧 Roseovoi
![4](https://github.com/AntonyCheng/spring-boot-init-template/assets/140489728/7078c026-c48b-4e5b-b5df-ba0443388233)
![5](https://github.com/AntonyCheng/spring-boot-init-template/assets/140489728/f28329e1-7a3c-4dd7-a956-588ac74d199a)

**Comment by AntonyCheng** [comment]
朋友 我乐意帮助你 但是你提供的vx有误 Roseovoi 查无此人

**Comment by Yaeovoi** [comment]
请再次搜索哈 我之前把通过微信号搜索关闭了
