### ISSUE TITLE
前端日志管理页面报错

### ISSUE THREAD

**Issue by YzwWh9327** [AntonyCheng/spring-boot-init-template#5]
后端出现空指针异常
![image](https://github.com/AntonyCheng/spring-boot-init-template/assets/39892371/288f1894-1777-48f6-ba9c-3fdf8e3695cc)
解决方法：
在数据库的t_log表中将log_user_id字段为null的数据删除。

**Comment by YzwWh9327** [comment]
1.建议在设计库表字段时，尽量设计为NOT NULL
2.在用户登录登录失败时，日志记录aop的debore方法拿不到登录失败的userId，因为你的逻辑是拿用户登陆成功后SaHolder持有的userId，所以写表时log_user_id字段为null

**Comment by AntonyCheng** [comment]
您好 感谢issues，目前日志模块还在完善和开发当中，预计在2.1.7正式版本会推出，这个问题我已经复现出来了，可能不止是登陆失败时会记录null数据，注册时应该也会记录空数据，目前暂时的改进策略就是当遇到空数据时给出该操作不需要记录用户信息的提示（如下图），但是这里会进一步优化！但是这俩天我正处于毕业时期，任务有些繁忙，如果有更好的想法可以提交PR，非常感谢您的使用！请拉取最新的代码！
![image](https://github.com/AntonyCheng/spring-boot-init-template/assets/88792183/4ef92686-2031-4b76-b55f-9f6115785e00)

**Comment by AntonyCheng** [comment]
> 1.建议在设计库表字段时，尽量设计为NOT NULL 2.在用户登录登录失败时，日志记录aop的debore方法拿不到登录失败的userId，因为你的逻辑是拿用户登陆成功后SaHolder持有的userId，所以写表时log_user_id字段为null

当前编码逻辑是符合当前数据库表设计的，比如删除用户的时候会强制删除用户的日志信息，但是这个建议会考虑或者采纳，后续请让该issues会处于open状态，一旦有成熟的设计方案这边会给出最终的设计思路，感谢使用该模板！😊
