### ISSUE TITLE
国际化不生效

### ISSUE THREAD

**Issue by sociometry** [AntonyCheng/spring-boot-init-template#6]
已在配置中开启国际化
将示例的I18nDemoController改成如下形式：
```
public class I18nDemoController {

    @GetMapping("/i18n")
    public R<String> welcome(@RequestParam String name) {
//        return R.ok(I18nManager.getMessage("msg_welcome", new String[]{name}));
        throw new CustomizeReturnException(ReturnCode.USERNAME_ALREADY_EXISTS);
    }
}
```
然后在`ReturnCode.java`中给`USERNAME_ALREADY_EXISTS`的文本替换为国际化形式
```
    USERNAME_ALREADY_EXISTS(11001, I18nManager.getMessage("opr_success")),
```

使用一种语言调用`/api/i18n`接口，切换为另一种语言再调用，可见返回的语言未切换
![图片](https://github.com/user-attachments/assets/1479edd1-4bc3-41ac-a4c3-3dd6dbc88f48)

**Comment by AntonyCheng** [comment]
稍等一阵！我现在手头没电脑，后端有报错么

**Comment by AntonyCheng** [comment]
> 已在配置中开启国际化 将示例的I18nDemoController改成如下形式：
> 
> ```
> public class I18nDemoController {
> 
>     @GetMapping("/i18n")
>     public R<String> welcome(@RequestParam String name) {
> //        return R.ok(I18nManager.getMessage("msg_welcome", new String[]{name}));
>         throw new CustomizeReturnException(ReturnCode.USERNAME_ALREADY_EXISTS);
>     }
> }
> ```
> 
> 然后在`ReturnCode.java`中给`USERNAME_ALREADY_EXISTS`的文本替换为国际化形式
> 
> ```
>     USERNAME_ALREADY_EXISTS(11001, I18nManager.getMessage("opr_success")),
> ```
> 
> 使用一种语言调用`/api/i18n`接口，切换为另一种语言再调用，可见返回的语言未切换 ![图片](https://private-user-images.githubusercontent.com/27913829/360895761-1479edd1-4bc3-41ac-a4c3-3dd6dbc88f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjIwNjksIm5iZiI6MTcyNDQyMTc2OSwicGF0aCI6Ii8yNzkxMzgyOS8zNjA4OTU3NjEtMTQ3OWVkZDEtNGJjMy00MWFjLWE0YzMtM2RkNmRiYzg4ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDE0MDI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3M2M0MGY4NzIzZDQxOTAwN2U5NmYwZTM1NTcwZmExOWYxOTQ3NTM2ZDE5ZGMzMzA4MWUyNDRkNTA5NjVjMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YYlXgS1vEAKy3-FIjhRnvCEA7alVY3ryq4JFhxPU4SA)

这个地方目前推测是拦截器没有处理异常而导致的错误，你先不要修改ReturnCode中的内容，目前不知道原因是什么，猜测是SpringBoot国际化在枚举中会出问题，先试试下面这种写法：
```java
@GetMapping("/i18n")
public R<String> welcome(@RequestParam String name) {
//        return R.ok(I18nManager.getMessage("msg_welcome", new String[]{name}));
    throw new CustomizeReturnException(ReturnCode.FAIL, I18nManager.getMessage("opr_fail"));
}
```

**Comment by AntonyCheng** [comment]
我先查查原因和相关的写法，这个国际化模块我挺旧没更新了，感觉优化的点挺多的，这边尝试抽取一下新的需求。

**Comment by sociometry** [comment]
是的，如果不用枚举里的就没问题。有啥临时解决方案吗？换个数据结构？

**Comment by AntonyCheng** [comment]
> 是的，如果不用枚举里的就没问题。有啥临时解决方案吗？换个数据结构？

临时解决方案就是先修改全局异常类中的输出表述，把“==>[]”这个结构给删去（这个地方我也是早想修改了，搞忘当时为什么要这么进行一场输出），然后选择不在枚举类中使用，而在业务代码里返回，至于方案，我今天调研一下，尽早回复你

**Comment by sociometry** [comment]
嗯嗯，谢谢，麻烦您了

**Comment by AntonyCheng** [comment]
> 已在配置中开启国际化 将示例的I18nDemoController改成如下形式：
> 
> ```
> public class I18nDemoController {
> 
>     @GetMapping("/i18n")
>     public R<String> welcome(@RequestParam String name) {
> //        return R.ok(I18nManager.getMessage("msg_welcome", new String[]{name}));
>         throw new CustomizeReturnException(ReturnCode.USERNAME_ALREADY_EXISTS);
>     }
> }
> ```
> 
> 然后在`ReturnCode.java`中给`USERNAME_ALREADY_EXISTS`的文本替换为国际化形式
> 
> ```
>     USERNAME_ALREADY_EXISTS(11001, I18nManager.getMessage("opr_success")),
> ```
> 
> 使用一种语言调用`/api/i18n`接口，切换为另一种语言再调用，可见返回的语言未切换 ![图片](https://private-user-images.githubusercontent.com/27913829/360895761-1479edd1-4bc3-41ac-a4c3-3dd6dbc88f48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDA1MTcsIm5iZiI6MTcyNDY0MDIxNywicGF0aCI6Ii8yNzkxMzgyOS8zNjA4OTU3NjEtMTQ3OWVkZDEtNGJjMy00MWFjLWE0YzMtM2RkNmRiYzg4ZjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDAyNDMzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2NmJhNzVkNGVhMmU3OTE4NmM2OWE0MTNiNzRhYTI4ZWU0YTQyMjM5YTYwMTIyYWU1N2FjZTcyYzM0YTE3MTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wX425Crbcjk57i3Bp5xQ8lQd_An3yTim3w-UnQMzPG8)

**新版本已经推送master分支**：这个地方不能进行国际化的原因是因为枚举属于静态内容，无法对其进行动态修改，所以最后的结果会一直不变，现在有一个取巧思路是在枚举类实例化之前进行国际化，所以我在ReturnCode中加入了toI18n()方法（这里和通用类耦合了，所以在配置文件中把国际化的开关取消了），但是感觉对于字典构造还是很麻烦，所以我在测试类中写了一个初始化系统国际化键值对内容的方法，把打印内容粘贴复制到字典文件里就行，你看一下还有没有更好的思路或者需求，具体可能看看README.md关于国际化的说明或者测试Controller。

**Comment by AntonyCheng** [comment]
> > 是的，如果不用枚举里的就没问题。有啥临时解决方案吗？换个数据结构？
> 
> 临时解决方案就是先修改全局异常类中的输出表述，把“==>[]”这个结构给删去（这个地方我也是早想修改了，搞忘当时为什么要这么进行异常输出），然后选择不在枚举类中使用，而在业务代码里返回，至于方案，我今天调研一下，尽早回复你

异常输出这个地方我还没有修改，因为目前没有想起当时这么做的原因是什么，我还需要一些时间确认一下

**Comment by sociometry** [comment]
谢谢！这样确实有效了，唯一可惜的是要慢慢给各个ReturnCode加上toI18n()了应该

**Comment by AntonyCheng** [comment]
> 谢谢！这样确实有效了，唯一可惜的是要慢慢给各个ReturnCode加上toI18n()了应该

不用谢，对模版有什么建议或者需求可以随时提，另外国际化本应该从项目规划之初进行设计，可以在IDEA中使用ctrl+shift+r进行快速替换，应该也不会很占用时间。
